#!groovy

node{
    stage('initialization Stage'){
        checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/1994newbie/Python-Jenkins.git']]])
    }
    stage('Provision Stage'){
        sh 'chmod -R 777 ./venv '
    }
    stage('Execution Stage'){
        sh """
        . ./venv/bin/activate
        pip install -r requirements.txt
        """
    }
    stage('Test Stage'){
        sh """
        . ./venv/bin/activate
        python ./Python/sample.py
        """
    }
    stage('Cleanup Stage'){
        
    }
}
